version: '3.9'

services:

  database:
    image: 'postgres:14-alpine'
    container_name: 'postgres-db'
    environment:
      - POSTGRES_USER=npca
      - POSTGRES_PASSWORD=npca
      - POSTGRES_DB=npca
    volumes:
      - type: bind
        source: ./init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
